### ISSUE TITLE
Where can I pass `allowComments: true`?

### ISSUE THREAD

**Issue by buhodev** [TorstenDittmann/svelte-markdoc-preprocess#16]
Hey, thanks for your work on this library 😄 

Markdoc doesn't support not rendering comments [by default](https://markdoc.dev/docs/syntax#comments). I wonder where can I pass that option using the svelte-markdoc-preprocess?

**Comment by TorstenDittmann** [comment]
Hey 👋🏻 

Let me add that feature 🙂

**Comment by TorstenDittmann** [comment]
1.1.0 just released where you can pass that as an option:

```js
markdoc({
    allowComments: true,
})
```
