### ISSUE TITLE
How to use named slots?

### ISSUE THREAD

**Issue by shyakadavis** [TorstenDittmann/svelte-markdoc-preprocess#51]
Hi, @TorstenDittmann 

I'm a completely new to Markdoc, but I'm finding it as something I'd be willing to use henceforth. Thank you for the package.

That said, I ran into some trouble trying to use `name slots` for my component.

Do you mind sharing how I can achieve this?

For context, I am building trying to create a `Playground` component, whose default slot could be filled with the rendered markup of that component, and the code snippet for the said components is conditionally rendered like the behavior of accordions.

Basically, I want the ability to wrap my code snippets in a named `code` slot, and also introduce some other component that will fill a `message` slot, for example.

Here is a simplified version of what I'm trying to achieve.

```markdoc
---
title: "Dot Pattern | Experiments"
---

{% playground %}
<!-- This is the default/rendered markup -->
{% dotpattern /%}

<!-- This would fill the `message` slot -->
{% message slot="message" description="Some message"  %}

<!-- This would fill the `code` slot -->
```html
<div
class="min-h-[256px] w-full bg-[radial-gradient(hsl(var(--foreground))_1px,_transparent_0)] bg-[length:8px_8px]"
/>
.```
{% /playground %}
```

And while I have you, do you any idea how to use https://github.com/antfu/shikiji or https://github.com/shikijs/shiki for syntax highlighting? 

Thank you.

**Comment by TorstenDittmann** [comment]
There's currently no syntax from from Markdoc itself that would support named slots. You could try to achieve it with nested components and set/getContext 👍🏻 

For example at Appwrite.io we achieved Multicode snippets like this:

```md
{% multicode %}
```js
// some JS
```
```php
// some PHP
```
```swift
// some Swift
```
{% /multicode %}

For reference:
https://github.com/appwrite/website/blob/main/src/markdoc/tags/MultiCode.svelte
https://github.com/appwrite/website/blob/main/src/markdoc/nodes/Fence.svelte

Probably the ESM rewrite of shiki will be the easiest to write 👍🏻 You basically need to add a node for the `Fence` tag.

**Comment by shyakadavis** [comment]
Hi, @TorstenDittmann 

Thanks for taking the time.

I'll be frank, most of what you said went over my head. I tried implementing what I want referencing those links to achieve the nested components and set/getContext, but couldn't make it.

I'm going to ask for an unreasonable request, but do you mind helping me out with that named slots workaround?

If you have the time, I have set up a repro/demo of what I want to achieve here: https://svelte-markdoc.pages.dev/
Repo is here as well: https://github.com/shyakadavis/svelte-markdoc

Thanks for the consideration.

**Comment by TorstenDittmann** [comment]
I can take a look in the following week 👍🏻

**Comment by shyakadavis** [comment]
Thank you very much, in advance.

Looking forward to it.

**Comment by TorstenDittmann** [comment]
Unfortunately I don't have the time to help out right now :-/

I'll come back to this once I do 🙏🏻
